### ISSUE TITLE
Milestone 9.1: Android App Development

### ISSUE THREAD

**Issue by Into-The-Grey** [Into-The-Grey/gh-nextjs-app#14]
### Tasks:
- [ ] Task 1: Design a minimal version of the website for Android
- [ ] Task 2: Integrate AI model and notification system into the app
- [ ] Task 3: Implement search functionality for technicians
- [ ] Task 4: Use the app for two-factor authentication for the website
