### ISSUE TITLE
Milestone 1.2: Basic Website Structure

### ISSUE THREAD

**Issue by Into-The-Grey** [Into-The-Grey/gh-nextjs-app#3]
### Tasks:
- [ ] Task 1: Design and implement the homepage using Next.js with the app importer
- [ ] Task 2: Develop user registration and authentication with Next.js, React, and Node.js
- [ ] Task 3: Set up basic HTTP protocol with Nginx
