### ISSUE TITLE
Milestone 3.1: Define User Roles

### ISSUE THREAD

**Issue by Into-The-Grey** [Into-The-Grey/gh-nextjs-app#6]
### Tasks:
- [ ] Task 1: Create user roles in the database
  - [ ] Sub-task 1: Expert
  - [ ] Sub-task 2: Admin
  - [ ] Sub-task 3: Moderator
  - [ ] Sub-task 4: Developer
  - [ ] Sub-task 5: Helper
  - [ ] Sub-task 6: Content Manager
  - [ ] Sub-task 7: SEO Specialist
  - [ ] Sub-task 8: Community Manager
  - [ ] Sub-task 9: Super Admin
  - [ ] Sub-task 10: User
  - [ ] Sub-task 11: Guest
